### ISSUE TITLE
Bug: Pressing 'Recent' crashes the app when Replays folder isn't present

### ISSUE THREAD

**Issue by weiyuan95** [ThereGoesMySanity/osuMissAnalyzer#14]
Exception log
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\osu!\Replays'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles()
   at OsuMissAnalyzer.UI.UIReplayLoader.LoadReplay()
   at OsuMissAnalyzer.UI.UIReplayLoader.Load(String replayFile, String beatmapFile)
   at OsuMissAnalyzer.UI.Program.Main(String[] args)
```

Repro steps: I'm on a (relatively) new install of Osu! and haven't actually exported any replays before, meaning that I dont have a `osu!/Replays` dir. Pressing the recent button leads to the error above.

Expected behavior: Based on the How To Use section in the README, I don't need to save/export any replays - my 5 recent plays can be analyzed

Creating that directory manually, or exporting a replay (which creates `osu!/Replays`) fixed the problem for me.

My guess is that you're always assuming the Replays dir is present in this line of code https://github.com/ThereGoesMySanity/osuMissAnalyzer/blob/c809d203b6b1ad8008713d8387e21d529528a747/OsuMissAnalyzer.UI/UIReplayLoader.cs#L67

**Comment by ThereGoesMySanity** [comment]
Yep - that line was the problem. Will be fixed next version.
