### ISSUE TITLE
MissAnalyzer crashes when a beatmap can't be parsed

### ISSUE THREAD

**Issue by ThereGoesMySanity** [ThereGoesMySanity/osuMissAnalyzer#30]
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at BMAPI.v1.Beatmap.Parse(String bm)
   at BMAPI.v1.Beatmap..ctor(String beatmapFile)
   at OsuDbAPI.Beatmap.Load(String songsFolder)
   at OsuMissAnalyzer.UI.Options.GetBeatmapFromHash(String mapHash)
   at OsuMissAnalyzer.UI.UIReplayLoader.LoadBeatmap(Replay replay, Boolean dialog)
   at OsuMissAnalyzer.UI.UIReplayLoader.<LoadReplay>b__25_5(Replay re)
   at OsuMissAnalyzer.UI.UIReplayLoader.LoadReplay()
   at OsuMissAnalyzer.UI.UIReplayLoader.Load()
   at OsuMissAnalyzer.UI.App.Load(UIReplayLoader loader)
```
Analyzer should handle exception instead of crashing

**Comment by ThereGoesMySanity** [comment]
Fixed in v1.6.2
